message(STATUS "构建信息")
message(STATUS "项目路径: ${PROJECT_SOURCE_DIR}")
message(STATUS "cpp版本: ${CMAKE_CXX_STANDARD}")
message(STATUS "模式: ${CMAKE_BUILD_TYPE}")
message(STATUS "编译器: ${CMAKE_CXX_COMPILER}")
message(STATUS "编译器版本: ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "平台: ${CMAKE_SYSTEM_NAME}")
message(STATUS "平台架构: ${CMAKE_SYSTEM_PROCESSOR}")
message(STATUS "平台版本: ${CMAKE_SYSTEM_VERSION}")
